### ISSUE TITLE
Linux 运行报错

### ISSUE THREAD

**Issue by badboycxcc** [SevenC-base/Xray_Scripts#1]
linux 运行报错，无法写入xlsx文件，
修改建议，第145行代码

```
windows
ll = dir1.split ("\\")[-1]

linux
ll = dir1.split ("/")[-1]
```

**Comment by SevenC-base** [comment]
好的，谢谢老板补充！

**Comment by SevenC-base** [comment]
> linux 运行报错，无法写入xlsx文件， 修改建议，第145行代码
> 
> ```
> windows
> ll = dir1.split ("\\")[-1]
> 
> linux
> ll = dir1.split ("/")[-1]
> ```

好的，谢谢老板补充！
